# Generated by Django 5.0.2 on 2024-02-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wallet_active_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
