# Generated by Django 5.0.2 on 2024-02-23 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wallet_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickercache',
            name='cached_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
